/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EntryId = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const DiaryEntry = IDL.Record({
  'id' : EntryId,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'moodTags' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [EntryId],
      [],
    ),
  'deleteEntry' : IDL.Func([EntryId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntriesByPage' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(DiaryEntry)],
      ['query'],
    ),
  'getEntry' : IDL.Func([EntryId], [IDL.Opt(DiaryEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchEntries' : IDL.Func([IDL.Text], [IDL.Vec(DiaryEntry)], ['query']),
  'updateEntry' : IDL.Func(
      [EntryId, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EntryId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const DiaryEntry = IDL.Record({
    'id' : EntryId,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'moodTags' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [EntryId],
        [],
      ),
    'deleteEntry' : IDL.Func([EntryId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntriesByPage' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(DiaryEntry)],
        ['query'],
      ),
    'getEntry' : IDL.Func([EntryId], [IDL.Opt(DiaryEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchEntries' : IDL.Func([IDL.Text], [IDL.Vec(DiaryEntry)], ['query']),
    'updateEntry' : IDL.Func(
        [EntryId, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };